### ISSUE TITLE
Bulbs do not display full range of colour options

### ISSUE THREAD

**Issue by samuel-matthews** [SeydX/homebridge-fritz-platform#133]
Hello, 
I realise that colour and dimming options are a recent change, but I seem to have an issue with selecting near white colours within the homekit UI?

**Comment by samuel-matthews** [comment]
Sorry, just realised that this is an option. You just require a longpress on the light option in the homekit. Sorry!

**Comment by SeydX** [comment]
What kind of issue? Does HomeKit not accept the selected color?

**Comment by samuel-matthews** [comment]
![RPReplay_Final1605914112](https://user-images.githubusercontent.com/58654668/99859556-a8ab0f80-2b90-11eb-98cc-4a8dc7dc02c1.gif)
Yeah, something like that. I select the colour I wish and after sending the request it defaults to a random colour. 

This is what it looks like in the logs
<img width="929" alt="Screenshot 2020-11-21 at 00 32 24" src="https://user-images.githubusercontent.com/58654668/99859680-0b9ca680-2b91-11eb-9347-ed13bbaf21c4.png">

**Comment by SeydX** [comment]
@samuel-matthews 

should be fixed with v5.0.14

**Note**

The Fritz DECT 500 still does not support the full color/temperature range as you can see below. The Plugin adjusts itself automatically to the nearest color/temperature

![fb_color](https://user-images.githubusercontent.com/34152761/99906425-65a78400-2cd7-11eb-8f99-ab9046e8b911.JPG)
![fb_cw](https://user-images.githubusercontent.com/34152761/99906429-66d8b100-2cd7-11eb-83d8-72b8166368c6.JPG)

**Comment by samuel-matthews** [comment]
Perfect! Let me know if I can do anything to help test. Best, Sam
