### ISSUE TITLE
Fritz!Dect 301 Auto Offset via MQTT

### ISSUE THREAD

**Issue by Tobix99** [SeydX/homebridge-fritz-platform#149]
**Is your feature request related to a problem? Please describe.**
Hey, so there is a feature in the Fritz!Box to take a DECT 200 and act as an external offset sensor. But you can also specify an manual offset.

**Describe the solution you'd like**
 So my plan is to take a Zigbee sensor (which I already own) and act as the offset sensor. So that if I publish in a Topic the current Sensor value the offset ist calculated and added. The Plugin would use the API/Webinterface to make the call and set the new offset.

**Comment by Tobix99** [comment]
So I've looked into the AVM SmartHome API and did not find any command to set a offset temperature. So maybe it can be done via a HTTP Request straight to the WebInterface (I've read, that there is something similar already used, but can't find it anymore).

**Comment by jemcraver** [comment]
I think, I did what you need. This small (quick'n'dirty) script runs on my pi an is called periodically by Homekit with the temp (multiplied by 10 to avoid decimals) of the sensors as get-params. 

It then sets the offset value of the fritz dect thermostats (it's working with the DECT 301 an the COMET DECT). I could not directly fake an external sensor, so I had to calculate the offset each time. As external Sensor I use Cleargrass Qingping Homekit compatible Sensors. 
For the HTTP-requests you need to set more data in the content, than just the offset, otherwise it won't work.

It's now running in my home for 3 months without problems, so maybe it's a way to implement it similar in the homebridge plugin? It's basically just a call of a script. 


<?php
$fritz_host = 'xxx';
$fritz_url = 'http://' . $fritz_host . '/login_sid.lua';
$fritz_user = 'xxx'; //optional
$fritz_pwd = 'xxx';
$with_debug_output = false;

$output="\n".date("Y-m-d H:i:s")."\n";

// Get Challenge-String
$tmp = simplexml_load_string(file_get_contents($fritz_url));
if ($tmp->BlockTime > 0) {
	sleep($tmp->BlockTime);
	$tmp = simplexml_load_string(file_get_contents($fritz_url));
}

if ($with_debug_output) {
print_r('Got challenge: ' . $tmp->asXML() . PHP_EOL);
}
$challenge = $tmp->Challenge;
// Get SID
$challenge_str = $challenge . '-' . $fritz_pwd;
$md_str = md5(iconv("UTF-8", "UTF-16LE", $challenge_str));
$response = $challenge . '-' . $md_str;
$tmp = simplexml_load_string(file_get_contents($fritz_url . '?user=' .
$fritz_user . '&response=' . $response));
if ($with_debug_output) {
print_r(' Got session ID: ' . $tmp->asXML() . PHP_EOL);
}

$sid = $tmp->SID;

//Get all devices

$options = array(
        'http' => array(
        'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
        'method'  => 'POST',
        'content' => '?xhr=1&lang=de&page=sh_dev&xhrId=all&no_sidrenew='
    	)
);

$context  = stream_context_create($options);

$set_offset_url='http://' . $fritz_host . '/data.lua?sid='.$sid;
$res = json_decode(file_get_contents($set_offset_url, false, $context));

$devices = $res->data->devices;

$dev_temp = array();

foreach ($devices as $device)
{
	$dev_temp[$device->id] = $device->units[1]->skills[0];
}



//print_r($dev_temp);

//Devices [nr] => offset
/*

print_r($dev_temp);
 [17] => stdClass Object  // WZ 1
        (
            [offset] => -4.5
            [type] => SmartHomeTemperatureSensor
            [currentInCelsius] => 21.5
        )

    [16] => stdClass Object  //WZ 2
        (
            [offset] => -5
            [type] => SmartHomeTemperatureSensor
            [currentInCelsius] => 21.5
        )

    [18] => stdClass Object /Bad
        (
            [offset] => -3
            [type] => SmartHomeTemperatureSensor
            [currentInCelsius] => 25.5
        )

    [19] => stdClass Object  //KiZi 1
        (
            [offset] => -2
            [type] => SmartHomeTemperatureSensor
            [currentInCelsius] => 24.5
        )

    [20] => stdClass Object //Kizi 2
        (
            [offset] => 0
            [type] => SmartHomeTemperatureSensor
            [currentInCelsius] => 26.5
        )

$offset = -5;

*/


//Temperatur-Sensoren per Get kriegen

$tmp_wz = (($_REQUEST["temp_wz"]>=50)&&($_REQUEST["temp_wz"]<500))?$_REQUEST["temp_wz"]/10:20;
$tmp_kizi = (($_REQUEST["temp_kizi"]>=50)&&($_REQUEST["temp_kizi"]<500))?$_REQUEST["temp_kizi"]/10:20;

//aktuelle Temperaturen $t am Thermostat


$t = array();

$output.="Wohnzimmer: {$tmp_wz}\nKinderzimmer: {$tmp_kizi}\n";

$out = array();

foreach ($dev_temp as $id=>$val) {
	$t[$id] = $val->currentInCelsius - $val->offset;
	$out[$id] = "{$id}:\t HK: {$t[$id]}  \t Offset 0: {$val->offset} \t Raum 0: {$val->currentInCelsius} \t";
}


//$output .= print_r ($t,true);
//$output .= print_r ($_REQUEST,true);

$neu[17] = $tmp_wz-$t[17];
$out[17].= "Offset 1: {$neu[17]}\n"; 
$neu[16] = $tmp_wz-$t[16];
$out[16].= "Offset 1: {$neu[16]}\n"; 
$out[18].= "\n"; 
$neu[20] = $tmp_kizi-$t[20];
$out[20].= "Offset 1: {$neu[20]}\n"; 
$neu[19] = $tmp_kizi-$t[19];
$out[19].= "Offset 1: {$neu[19]}\n"; 

$output .= $out[16].$out[17].$out[18].$out[19].$out[20]."\n";


foreach ($neu as $id => $offset)
{

$options = array(
        'http' => array(
        'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
        'method'  => 'POST',
        'content' => '?' 
						.'&device='.$id
						.'&view='
						.'&back_to_page=sh_dev'
						.'&Offset='.$offset
						.'&validate=apply'
						.'&xhr=1'
						.'&useajax=1'
    	)
);




$context  = stream_context_create($options);

$set_offset_url='http://' . $fritz_host . '/net/home_auto_hkr_edit.lua?sid='.$sid;
echo file_get_contents($set_offset_url, false, $context);

$options = array(
        'http' => array(
        'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
        'method'  => 'POST',
        'content' => '?xhr=1'
						.'&lang=de'
						.'&no_sidrenew='
						.'&device='.$id
						.'&view='
						.'&back_to_page=sh_dev'
						.'&ule_device_name='
						.'&WindowOpenTrigger='
						.'&WindowOpenTimer='
						.'&tempsensor='
						.'&Roomtemp='
						.'&ExtTempsensorID='
						.'&Offset='.$offset
						.'&apply='
						.'&oldpage=%2Fnet%2Fhome_auto_hkr_edit.lua'
    	)
);


$context  = stream_context_create($options);

$set_offset_url='http://' . $fritz_host . '/data.lua?sid='.$sid;
echo file_get_contents($set_offset_url, false, $context);

}


// Logout
$tmp = simplexml_load_string(file_get_contents($fritz_url . '?logout=1&sid='
. $sid));
if ($with_debug_output) {
print_r(' Logout: ' . $tmp->asXML() . PHP_EOL);
}

file_put_contents("/var/www/html/out.txt",$output,FILE_APPEND);
?>

**Comment by Tobix99** [comment]
Thanks for your help, but after seeing the long update time to change the temperature, I got the HomematicIP thermostats, which can do the offset thing via the Bridge and many things more, the Fritz couldn’t. Also the Update time for the temperature is like 5-10 seconds with these.

**Comment by Argelbargel** [comment]
Hi @jemcraver, thanks for posting your solution! It helped my in a big way to implement my own solution to update the temperature offsets based on my OpenHAB-setup: https://gist.github.com/Argelbargel/bfbcbc09e90bf2bac3d9a3ccaeb2506b

**Comment by zoulaim** [comment]
Hi, thanks for the script. I'm fairly new to Raspi, I have homebridge with Homebridge Fritz Platform  and zigbee2mqtt installed. Is there a plugin I can use to connect a zigbee temp sensor as offset sensor? If not, where do I put jemcraver's script and which parts do I have to edit?
