### ISSUE TITLE
FRITZ!DECT 440 Support

### ISSUE THREAD

**Issue by Sv3n5on** [SeydX/homebridge-fritz-platform#170]
**Is your feature request related to a problem? Please describe.**

The switch can be defined, is displayed in the Home app, but cannot be used. 

**Describe the solution you'd like**

Please support for the device and its 4 channels 

**Describe alternatives you've considered**

**Additional context**

The device also measures temperature and humidity.

**Comment by SeydX** [comment]
AVM does not currently support triggering the available buttons via the API.

Currently it is only possible to query the API WHEN the last press event was.

Theoretically, it is possible to listen for these events via polling, but there would be a delay from pressing the switch to detection by HomeKit due to polling

**Comment by SeydX** [comment]
Added support for DECT 400/440 in v6.0.0-beta.36 with own polling timer to listen better to events

**Comment by SeydX** [comment]
![B5D9346F-CEA3-4F69-9EB5-EED89CB7F548](https://user-images.githubusercontent.com/34152761/122574517-01bc2280-d050-11eb-800c-ecbc33663711.png)

**Comment by SeydX** [comment]
Closing this issue since it was included in the beta (see last comment) and to keep track of which feature requests are still open.

**Comment by SeydX** [comment]
#191
