### ISSUE TITLE
Not working when fritzbox connected to inet via second router lan

### ISSUE THREAD

**Issue by recordfactory** [SeydX/homebridge-fritz-platform#64]
If the fritzbox gets internet via a second router's (non fritz lte router here) lan or wifi connection, the plugin doesn't work. If type "repeater" is used, it asks for a master device, even if the box is the master. 
If box type is "dsl" or "cable", it throws this error:
```
569Z FritzPlatform Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
```
**To Reproduce**
See above

**Expected behavior**
Would be great if the plugin has an option for type: "lan" and/or "wifi"

**Comment by recordfactory** [comment]
7490

**Comment by SeydX** [comment]
Do you have access to the FritzBox web interface?

**Comment by recordfactory** [comment]
Yes.

**Comment by SeydX** [comment]
can u open the tr064 endpoint with following link

http://HOST:49000/tr064desc.xml

HOST = the same address as fritzbox web interface

**Comment by recordfactory** [comment]
That throws a 404, document not found.
Should the plugin run to get that doc?

**Comment by SeydX** [comment]
No you don’t need the plugin.

Maybe it is a port issue? U enabled the tr064 api on your fritzbox?

**Comment by recordfactory** [comment]
Ok, stealth mode was the culprit. Now its there. Which info do you need? I don't want to publish the whole doc here. Btw, thank you very much for taking care of the issue!

**Comment by SeydX** [comment]
If you have access to the doc, the plugin should be able to connect to the endpoint

the host in the config must be the same as the address u give to enter the fritzbox web interface

btw. could u try it with v5 of this plugin pls

``sudo npm i -g homebridge-fritz-platform@beta --unsafe-perm``

i also recommend to adjust the config with [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x)

otherwise here is the [example-config.json](https://github.com/SeydX/homebridge-fritz-platform/blob/beta/example/example-config.json)
