### ISSUE TITLE
Option to mark the power switch as "read-only"

### ISSUE THREAD

**Issue by flobernd** [SeydX/homebridge-fritz-platform#9]
Hi there,

could you please add an option that marks the power-switch of the Fritz!Box device as read-only. I do not need to switch it off remotely and I already pressed the switch once by accident 😛 

I don't know if the HAP specification allows to revoke write-access to the `On` characteristic, but as a workaround you could just ignore the `Set` command in your plugin for this specific power switch.

Best regards

**Comment by SeydX** [comment]
Added into todo list

**Comment by SeydX** [comment]
Added in v3.0.2

**Comment by SCoe2k** [comment]
Hi,

Cannot find the read-only function in readme, but very interested. Please be so kind and explain option to be set in order to disable power-switch.

**Comment by ewpospo** [comment]
> Added in v3.0.2

Hi,  
@seydx 

I am currently using the latest version of the plugin (v6.0.19) with the following configuration:

``` json
"options": {
    "wifi_2ghz": "switch",
    "wifi_5ghz": "switch",
    "wifi_guest": "switch",
    "led": "switch"
}
```

and also:

``` json
"readOnly": true
``` 

My goal is to have the WiFi and LED switches visible in Apple Home only for monitoring/status purposes, but without the ability to accidentally toggle them.

Unfortunately, despite readOnly: true, the switches are still fully writable in HomeKit and I can still turn WiFi on/off accidentally.

Is readOnly currently only supported for SmartHome/DECT devices, or should it also work for:
- wifi_2ghz
- wifi_5ghz
- wifi_guest
- led

switches?

If not supported yet, would it be possible to add proper read-only support for these router switches in the future?

I think this would be very useful because many users only want to monitor WiFi states in HomeKit without risking accidental deactivation of their network.

Thanks!
